name: cheffy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  flutter_support_pack: ^1.1.0
  provider: ^6.0.4
  stacked: ^3.0.0
  stacked_services: ^0.9.5
  stacked_themes: ^0.3.9
  package_info: ^2.0.2
  dio: ^4.0.6
  dartz: ^0.10.1
  fresh_dio: ^0.3.2
  rxdart: ^0.27.5
  reactive_forms: ^14.1.0
  reactive_image_picker: ^0.12.0
  reactive_flutter_rating_bar: ^0.4.0
  reactive_phone_form_field: ^0.10.0
  reactive_pin_code_fields: ^0.4.0
  reactive_date_range_picker: ^0.5.0
  reactive_date_time_picker: ^0.5.0
  reactive_range_slider: ^0.5.0
  shimmer: ^2.0.0
  r_dart_library: ^0.4.1
  flutter_secure_storage: ^6.0.0
  infinite_scroll_pagination: ^3.2.0
  connectivity_plus: ^3.0.2
  responsive_builder: ^0.4.2
  geolocator: ^9.0.1
  easy_localization: ^3.0.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1
  flutter_chat_ui: ^1.6.4
  dotted_border: ^2.0.0+2
  google_maps_flutter: ^2.2.1
  image_picker: ^0.8.5+3
  expandable_bottom_sheet:
  font_awesome_flutter: ^10.2.1
  timeago_flutter: ^1.2.0
  carousel_slider: ^4.1.1
#  flutter_svg:

  # Firebase
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.3
  firebase_crashlytics: ^3.0.3

  google_sign_in: ^5.4.2
  # flutter_facebook_auth: ^5.0.0+2

dependency_overrides:
  firebase_auth_platform_interface: 6.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  
flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/3x/img_logo.png"
  remove_alpha_ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700